import Foundation

struct Moment: Identifiable, Equatable, Codable {
    let id: Int
    let title: String
    let text: String
}

extension Moment {
    var imageName: String {
        return "moment" + String(id)
    }
    
    static let allMoments: [Self] = [
        Moment(id: 1, title: "Michael Jordan's 'The Shot'", text: "On May 7, 1989, Michael Jordan delivered one of the most iconic moments in basketball history during Game 5 of the Eastern Conference First Round against the Cleveland Cavaliers. With the Chicago Bulls trailing by one point and just three seconds remaining, Jordan received an inbounds pass, dribbled past defenders, and launched a high-arching jumper over Craig Ehlo as the buzzer sounded. The shot swished through the net, securing a 101-100 victory and eliminating the Cavaliers from the playoffs. This moment, famously dubbed 'The Shot,' showcased Jordan’s clutch ability and marked a turning point in his career, propelling the Bulls toward their eventual dynasty. The image of Jordan leaping into the air in celebration remains etched in NBA lore.\n\nThe play was a culmination of Jordan’s growing legend, as he averaged 39.8 points per game in that series. For Cleveland, it was a devastating blow, adding to their reputation as a cursed franchise at the time. Ehlo, tasked with guarding Jordan, later reflected on the difficulty of defending such an unstoppable force. The Shot not only silenced the raucous Richfield Coliseum crowd but also signaled the beginning of Jordan’s postseason dominance. It’s a moment that continues to be replayed and celebrated as a defining example of basketball greatness."),
        
        Moment(id: 2, title: "Wilt Chamberlain's 100-Point Game", text: "On March 2, 1962, Wilt Chamberlain achieved an unparalleled feat by scoring 100 points in a single NBA game for the Philadelphia Warriors against the New York Knicks. Played in Hershey, Pennsylvania, before a modest crowd of 4,124, Chamberlain dominated from start to finish, shooting 36-for-63 from the field and an astonishing 28-for-32 from the free-throw line. The game ended with a 169-147 Warriors victory, but Chamberlain’s performance overshadowed everything else. Remarkably, no video footage exists—only a radio broadcast and a few photographs preserve the moment. The final minutes saw fans storm the court as Chamberlain chased the century mark, with his 100th point coming on a dunk with 46 seconds left.\n\nChamberlain’s record remains untouched, a testament to his physical dominance at 7’1” and his relentless scoring ability. That season, he averaged 50.4 points per game, another untouchable mark. The Knicks, helpless against him, rotated defenders to no avail, as Chamberlain exploited mismatches and his superior athleticism. The game’s stat sheet, preserved by a diligent scorekeeper, is now a prized artifact in basketball history. This moment solidified Chamberlain’s legacy as one of the game’s greatest, though it also sparked debates about his focus on individual stats over team success."),
        
        Moment(id: 3, title: "LeBron James' 2016 Finals Comeback", text: "In June 2016, LeBron James orchestrated one of the greatest comebacks in sports history, leading the Cleveland Cavaliers to an NBA Championship against the Golden State Warriors. The Warriors, who had set an NBA record with a 73-9 regular season, took a commanding 3-1 lead in the Finals. No team had ever recovered from such a deficit in the Finals, but James refused to relent. Over the next three games, he averaged 36.3 points, 11.7 rebounds, and 9.7 assists, including a 41-point masterpiece in Game 5. The turning point came in Game 7, when James made a chasedown block on Andre Iguodala with under two minutes left, preserving a tie score.\n\nKyrie Irving’s subsequent three-pointer gave Cleveland the lead, and the Cavs held on for a 93-89 victory on June 19, 2016. This triumph ended Cleveland’s 52-year championship drought across all major sports, igniting celebrations across Ohio. James, a native of Akron, earned Finals MVP honors, fulfilling his promise to bring a title home. The Warriors, stunned by the collapse, saw their historic season end in heartbreak. This series showcased James’ leadership, versatility, and sheer will, cementing his status as one of basketball’s all-time greats."),
        
        Moment(id: 4, title: "Magic vs. Bird 1979 NCAA Final", text: "On March 26, 1979, Magic Johnson’s Michigan State Spartans faced Larry Bird’s Indiana State Sycamores in the NCAA Championship game, a matchup that captivated the nation. Michigan State won 75-64, with Johnson earning Most Outstanding Player honors after scoring 24 points. The game drew a then-record 35.11 million viewers, making it the most-watched college basketball game ever. Bird, despite the loss, scored 19 points, though he struggled against Michigan State’s defense. This clash marked the beginning of a rivalry that would define the NBA in the 1980s, as both players went on to become legends with the Lakers and Celtics, respectively.\n\nThe significance of this game extended beyond the court, revitalizing interest in college basketball during a time when the sport needed a boost. Johnson’s charisma and Bird’s stoic brilliance contrasted perfectly, setting the stage for their professional battles. Indiana State entered the game undefeated at 33-0, adding to the drama, but Michigan State’s teamwork prevailed. The game’s legacy lies in its role as a launching pad for two of basketball’s biggest stars. Decades later, it’s remembered as a cultural milestone that reshaped the sport’s trajectory."),
        
        // Soccer
        Moment(id: 5, title: "Maradona's 'Hand of God'", text: "During the 1986 FIFA World Cup quarterfinal on June 22, Diego Maradona scored one of the most controversial goals in soccer history against England. In the 51st minute, with the score tied at 0-0, Maradona leapt to challenge goalkeeper Peter Shilton for a high ball and punched it into the net with his left hand. The referee, failing to see the infraction, allowed the goal, dubbing it the 'Hand of God' after Maradona’s cheeky post-match comment that it was scored 'a little with the head, and a little with the hand of God.' Just four minutes later, Maradona dazzled with the 'Goal of the Century,' dribbling past five defenders to score again. Argentina won 2-1, advancing en route to the title.\n\nThe match, held in Mexico City’s Azteca Stadium, was charged with political tension due to the Falklands War four years prior. England’s players and fans were outraged, but FIFA upheld the result, as video replay wasn’t yet in use. Maradona’s audacity and skill in that game solidified his legend, though the handball remains a polarizing moment. For Argentina, it was a triumphant act of defiance; for England, a bitter pill. This dual display of cunning and genius encapsulates Maradona’s complex legacy in soccer history."),
        
        Moment(id: 6, title: "Pelé’s 1970 World Cup Triumph", text: "In the 1970 FIFA World Cup final on June 21, Pelé led Brazil to a 4-1 victory over Italy, securing their third title and cementing his status as soccer’s greatest player. Held in Mexico, the tournament showcased Brazil’s flair, with Pelé scoring the opening goal in the final with a header off a Rivelino cross. He also assisted on two others, including Carlos Alberto’s iconic fourth goal. At 29, Pelé became the only player to win three World Cups (1958, 1962, 1970), retiring from international play with 77 goals in 92 matches. The game, broadcast in color for the first time, mesmerized a global audience.\n\nBrazil’s 1970 team is often hailed as the best ever, blending artistry and dominance. Pelé’s performance capped a career marked by resilience—he’d been injured in 1966—and brilliance. Italy, a defensive powerhouse, couldn’t contain Brazil’s attack, which included stars like Jairzinho and Tostão. The Jules Rimet Trophy was permanently awarded to Brazil after their third win, a fitting tribute to Pelé’s reign. This moment remains a pinnacle of soccer’s golden era, immortalizing Pelé as 'O Rei' (The King)."),
        
        Moment(id: 7, title: "Miracle of Istanbul", text: "On May 25, 2005, Liverpool FC staged an improbable comeback in the UEFA Champions League final against AC Milan at Istanbul’s Atatürk Stadium. Milan, led by Paolo Maldini and Hernán Crespo, surged to a 3-0 lead by halftime, seemingly securing the title. But Liverpool’s captain, Steven Gerrard, sparked a revival with a header in the 54th minute, followed by goals from Vladimír Šmicer and Xabi Alonso within six minutes, tying the score at 3-3. The match went to penalties, where goalkeeper Jerzy Dudek’s saves—mimicking Bruce Grobbelaar’s 1984 antics—clinched a 3-2 shootout win for Liverpool. It was their fifth European title.\n\nThe turnaround stunned the soccer world, as Milan boasted stars like Kaka and Andrea Pirlo. Liverpool’s fans, who sang 'You’ll Never Walk Alone' at halftime, played a role in lifting the team’s spirits. Manager Rafael Benítez’s tactical adjustments, including a double substitution, proved decisive. The match is celebrated as one of the greatest finals ever, a testament to resilience and belief. For Milan, it was a collapse that haunted them for years, while Liverpool’s triumph became a legend of the sport."),
        
        Moment(id: 8, title: "Messi’s 2022 World Cup Glory", text: "On December 18, 2022, Lionel Messi led Argentina to a FIFA World Cup victory against France in Qatar, ending a 36-year drought for his nation. The final, held at Lusail Stadium, saw Argentina take a 2-0 lead with goals from Messi and Ángel Di María, only for Kylian Mbappé to equalize with a late brace, forcing extra time. Messi scored again in the 108th minute, but Mbappé’s hat-trick leveled it at 3-3, leading to a penalty shootout. Argentina prevailed 4-2, with goalkeeper Emiliano Martínez making key saves. Messi, at 35, earned the Golden Ball as the tournament’s best player, scoring seven goals and assisting three.\n\nThe victory was Messi’s crowning achievement, silencing critics who pointed to his lack of a World Cup title. Argentina’s journey included a shocking loss to Saudi Arabia, making their recovery all the more remarkable. France, the defending champions, pushed to the limit, but Messi’s brilliance and leadership shone through. The final, watched by billions, is considered one of the greatest ever. For Messi, it completed a career that already included countless records, cementing his place alongside Pelé and Maradona."),
        
        // Hockey
        Moment(id: 9, title: "Miracle on Ice", text: "On February 22, 1980, the U.S. Olympic hockey team stunned the Soviet Union 4-3 in the Winter Olympics at Lake Placid, New York. The Soviets, winners of four straight Olympic golds, were a professional juggernaut, while the U.S. roster featured college players, coached by Herb Brooks. Down 3-2 entering the third period, Mark Johnson tied the game, and captain Mike Eruzione scored the go-ahead goal with 10 minutes left. Goaltender Jim Craig made 36 saves to preserve the lead as the crowd chanted 'U-S-A!' Al Michaels’ call—'Do you believe in miracles? Yes!'—became iconic. The U.S. went on to beat Finland for gold.\n\nThe game transcended sports, occurring amid Cold War tensions, symbolizing American grit against Soviet dominance. Brooks’ strategy—outskating the Soviets—defied expectations, as the U.S. had lost 10-3 to them in an exhibition weeks earlier. The victory galvanized a nation facing economic and political struggles. Decades later, it remains hockey’s most celebrated upset, a story of underdogs triumphing against all odds."),
        
        Moment(id: 10, title: "Wayne Gretzky’s 50 Goals in 39 Games", text: "On December 30, 1981, Wayne Gretzky shattered the NHL record for fastest 50 goals, scoring five against the Philadelphia Flyers in his 39th game of the season. Playing for the Edmonton Oilers, Gretzky entered the game with 45 goals and erupted for a hat trick, an empty-netter, and his 50th on a breakaway. The Oilers won 7-5, and the record eclipsed Maurice 'Rocket' Richard’s mark of 50 goals in 50 games, set in 1944-45. Gretzky finished the 1981-82 season with 92 goals, an untouchable NHL record. The feat showcased his unparalleled scoring prowess and vision.\n\nAt just 20 years old, Gretzky was already rewriting hockey history. The Flyers, a strong team, couldn’t contain him, as he exploited their defense with speed and precision. Fans at Northlands Coliseum erupted as he hit the milestone, cementing his nickname, 'The Great One.' The record-breaking night was a glimpse of Gretzky’s dominance—he’d win the Hart Trophy that year, his third of nine straight. This moment remains a benchmark for offensive excellence in hockey."),
        
        Moment(id: 11, title: "Bobby Orr’s Flying Goal", text: "On May 10, 1970, Bobby Orr scored one of hockey’s most famous goals, clinching the Stanley Cup for the Boston Bruins against the St. Louis Blues. In Game 4 of the Finals, tied at 3-3 in overtime, Orr took a pass from Derek Sanderson and fired it past Glenn Hall just 40 seconds in. As the puck hit the net, Blues defenseman Noel Picard tripped Orr, sending him airborne in a now-iconic image. The 4-3 victory gave Boston their first Cup since 1941, ending a 29-year drought. Orr, at 22, was named Finals MVP.\n\nThe goal highlighted Orr’s revolutionary style—combining defense and offense like no one before. He’d already won the Norris Trophy that year, the start of eight straight. The Bruins, powered by Orr and Phil Esposito, swept the Blues, but this moment defined the series. The photo of Orr soaring became a symbol of hockey artistry. For Boston fans, it was a cathartic triumph after years of near-misses, etching Orr into NHL immortality."),
        
        Moment(id: 12, title: "Sidney Crosby’s Golden Goal", text: "On February 28, 2010, Sidney Crosby scored the 'Golden Goal' for Canada against the U.S. in the Vancouver Olympics final. Tied 2-2 in overtime, Crosby called for a pass from Jarome Iginla and wristed it past Ryan Miller at 7:40, securing a 3-2 victory. The goal unleashed pandemonium across Canada, as the host nation reclaimed Olympic gold on home soil. Crosby, just 22 and captain of the Pittsburgh Penguins, became a national hero overnight. The game, pitting two hockey powerhouses, drew a record 27 million Canadian viewers.\n\nThe U.S. had forced overtime with a goal by Zach Parise with 24 seconds left in regulation, heightening the drama. Canada, favored to win, faced immense pressure after a shaky tournament start. Crosby’s clutch performance mirrored his NHL success—he’d already won a Stanley Cup in 2009. The victory was a defining moment for a generation of Canadian fans, echoing the 1972 Summit Series. For Crosby, it solidified his legacy as one of hockey’s all-time greats."),
        
        // Volleyball
        Moment(id: 13, title: "Karch Kiraly’s Olympic Gold", text: "In the 1984 Los Angeles Olympics, Karch Kiraly led the U.S. men’s volleyball team to its first Olympic gold, defeating Brazil 3-0 in the final. Kiraly, a 23-year-old standout, dominated with his spiking and serving, earning MVP honors. The U.S. went undefeated in the tournament, a feat made sweeter on home soil during a Cold War-era boycott by the Soviet bloc. Volleyball’s popularity surged in America, thanks to Kiraly’s flair and the team’s precision. This victory marked the start of a golden era for U.S. volleyball, with Kiraly as its poster boy.\n\nBefore 1984, the U.S. had never medaled in Olympic volleyball, making the win a breakthrough. Kiraly’s versatility—he later excelled in beach volleyball—set him apart. The final, played before a packed crowd at Long Beach Arena, showcased the sport’s growing appeal. Brazil, a rising power, couldn’t match the U.S.’s intensity. Kiraly’s legacy from this moment inspired generations, cementing his status as volleyball’s greatest player."),
        
        Moment(id: 14, title: "Brazil’s 2004 Olympic Dominance", text: "On August 29, 2004, Brazil’s men’s volleyball team won gold at the Athens Olympics, defeating Italy 3-1 in the final. Led by stars like Giba and Dante Amaral, Brazil showcased their attacking prowess and defensive resilience. They lost just one set in the entire tournament, a testament to their dominance. The victory marked Brazil’s second Olympic gold (after 1992), solidifying their status as a volleyball superpower. The final set, won 25-15, capped a performance that thrilled fans at the Peace and Friendship Stadium.\n\nItaly, a perennial contender, pushed hard but couldn’t overcome Brazil’s momentum. Coach Bernardo Rezende’s strategies maximized the team’s athleticism, setting a new standard for the sport. The win was a milestone in Brazil’s volleyball ascent, following years of near-misses. It also highlighted the country’s passion for the game, rivaling soccer in some regions. For the players, it was a career-defining triumph, celebrated wildly back home."),
        
        Moment(id: 15, title: "U.S. Women’s 2021 Olympic Victory", text: "On August 8, 2021, the U.S. women’s volleyball team won their first Olympic gold, defeating Brazil 3-0 in the Tokyo Games (delayed from 2020). Led by coach Karch Kiraly and stars like Jordan Larson, the U.S. dominated with scores of 25-21, 25-20, and 25-14. The victory came after decades of close calls—silvers in 1984, 2008, and 2012—and showcased a new generation of talent. Larson, named MVP, sealed the win with a final spike, ending her Olympic career on top. The U.S. hadn’t dropped a set in the knockout rounds, a rare feat.\n\nBrazil, the two-time defending champions, couldn’t match the U.S.’s precision and power. The win was a landmark for American volleyball, long overshadowed by the men’s 1980s success. Played without fans due to COVID-19, the triumph still resonated globally. Kiraly, a gold medalist as a player, became the first to win as both athlete and coach. For the U.S., it was a crowning moment, proving their women’s program had reached the pinnacle."),
        
        // Tennis
        Moment(id: 16, title: "Federer’s 2009 French Open Win", text: "On June 7, 2009, Roger Federer won the French Open, defeating Robin Soderling 6-1, 7-6(1), 6-4 to complete his career Grand Slam. The victory at Roland Garros, on clay where he’d struggled, ended years of frustration against Rafael Nadal. Federer, 27, had lost three straight French Open finals to Nadal, but Nadal’s upset loss to Soderling in the fourth round opened the door. Federer capitalized, dropping just one set all tournament. The win tied him with Pete Sampras at 14 Grand Slams, a record at the time.\n\nThe final was emotional—Federer teared up as the crowd roared, knowing he’d conquered his final frontier. Soderling, a surprise finalist, played well but couldn’t match Federer’s versatility. The victory silenced doubters who questioned Federer’s clay-court credentials. It also marked a resurgence after a tough 2008, reasserting his dominance. For tennis fans, it was a historic moment, cementing Federer’s claim as the greatest of his era."),
        
        Moment(id: 17, title: "Nadal’s 2008 Wimbledon Epic", text: "On July 6, 2008, Rafael Nadal defeated Roger Federer 6-4, 6-4, 6-7(5), 6-7(8), 9-7 in the Wimbledon final, ending Federer’s five-year reign. The match, lasting 4 hours and 48 minutes, is widely regarded as the greatest Grand Slam final ever. Nadal, the clay-court king, adapted to grass, breaking Federer’s serve at key moments. Rain delays stretched the match into near-darkness, with Nadal clinching it at 9:16 p.m. local time. It was his fifth Grand Slam and first outside the French Open.\n\nFederer, chasing a sixth straight Wimbledon, saved match points in the fourth set, forcing a fifth. The tension was palpable, with both players trading brilliance—Nadal’s topspin against Federer’s elegance. The Centre Court crowd was electrified, witnessing a clash of titans. Nadal’s victory shifted their rivalry, proving he could beat Federer anywhere. For tennis, it was a defining moment, showcasing the sport’s intensity and drama."),
        
        Moment(id: 18, title: "Serena’s 23rd Grand Slam", text: "On January 28, 2017, Serena Williams won the Australian Open, defeating her sister Venus 6-4, 6-4 for her 23rd Grand Slam title. Remarkably, Serena was pregnant with her daughter, Olympia, during the tournament, a fact revealed later. At 35, she broke Steffi Graf’s Open Era record, cementing her status as one of tennis’s greatest. The all-Williams final was their ninth in Grand Slams, showcasing their dominance. Serena dropped just one set all tournament, her power overwhelming opponents.\n\nVenus, 36, fought valiantly, but Serena’s precision prevailed in Melbourne. The win came after a challenging 2016, proving Serena’s resilience. Her pregnancy added a layer of awe—playing at such a level while expecting defied belief. The siblings’ embrace at the net was a touching moment, blending competition and love. For women’s tennis, it was a historic milestone, highlighting Serena’s unparalleled legacy."),
        
        Moment(id: 19, title: "Bjorn Borg’s 1980 Comeback", text: "On July 5, 1980, Bjorn Borg won his fifth straight Wimbledon title, defeating John McEnroe 1-6, 7-5, 6-3, 6-7(16), 8-6 in an epic final. The match’s fourth-set tiebreak, lasting 22 minutes and 34 points, saw McEnroe save five match points and Borg seven set points. Borg, the cool Swede, rallied in the fifth set, clinching it on his serve after 4 hours. It was his 11th Grand Slam, all on clay or grass. McEnroe’s fiery energy contrasted Borg’s calm, making it a classic.\n\nThe tiebreak is legendary—Centre Court held its breath as momentum swung wildly. Borg’s baseline game wore down McEnroe, who’d won the first set easily. The victory solidified Borg’s Wimbledon dynasty, a record later matched by Federer. McEnroe won the rematch in 1981, ending Borg’s streak, but 1980 remains their defining clash. For tennis, it was a showcase of skill and mental fortitude."),
        
        // Bicycling
        Moment(id: 20, title: "Eddy Merckx’s 1971 Hour Record", text: "On October 25, 1971, Eddy Merckx set a new hour record, cycling 49.431 kilometers at Mexico City’s high-altitude velodrome. The Belgian, already a Tour de France and Giro d’Italia champion, pushed a specially designed bike to its limit. He averaged over 30 mph, surpassing Ferdinand Schur’s 1958 mark by nearly a kilometer. Merckx, known as 'The Cannibal' for his relentless wins, collapsed from exhaustion afterward. The record stood for 12 years, a testament to his physical and mental strength.\n\nMexico City’s thin air aided speed but taxed endurance, making the feat grueling. Merckx trained meticulously, focusing on aerodynamics and pacing. Spectators watched in awe as he lapped the track 197 times. The record elevated cycling’s profile, showcasing its brutal beauty. For Merckx, it was another jewel in a career that included five Tour titles, cementing his legend."),
        
        Moment(id: 21, title: "Greg LeMond’s 1989 Tour Comeback", text: "On July 23, 1989, Greg LeMond won the Tour de France by eight seconds over Laurent Fignon in a dramatic final time trial. Trailing by 50 seconds entering the 24.5-kilometer stage, LeMond used aerodynamic handlebars—a rarity then—to gain time. He finished in 26:57, while Fignon, hampered by saddle sores, crossed in 27:55. The victory gave LeMond his second Tour title, a stunning recovery from a 1987 hunting accident that nearly killed him. He became the first American Tour winner (officially, after later disqualifications).\n\nFignon, the 1983 and 1984 champion, seemed poised to win until LeMond’s surge. The Paris finish on the Champs-Élysées was electric, with fans stunned by the razor-thin margin. LeMond’s comeback symbolized resilience—he’d been shot with 60 pellets two years prior. The time trial revolutionized cycling, popularizing aero tech. For the sport, it was a thrilling chapter, showcasing its unpredictability."),
        
        Moment(id: 22, title: "Pogacar’s 2020 Tour Upset", text: "On September 19, 2020, Tadej Pogacar overturned a 57-second deficit to win the Tour de France on the penultimate stage, a 36.2-kilometer time trial. The 21-year-old Slovenian finished in 55:55, beating leader Primoz Roglic by 1:56. Roglic, his compatriot, faltered under pressure, losing the yellow jersey he’d held for 11 days. Pogacar won the Tour in his debut, also taking the polka dot and white jerseys. The next day, he rode into Paris victorious, the youngest winner since 1904.\n\nThe upset shocked cycling—Roglic’s Jumbo-Visma team had dominated the race. Pogacar’s UAE Team Emirates bet on his climbing and time-trialing skills, which paid off spectacularly. Stage 20’s brutal climb up La Planche des Belles Filles tested both riders, but Pogacar thrived. The victory launched him as a superstar, following with a 2021 repeat. For fans, it was a breathtaking twist, proving the Tour’s unpredictability."),
        
        // Boxing
        Moment(id: 23, title: "Ali’s Rumble in the Jungle", text: "On October 30, 1974, Muhammad Ali reclaimed the heavyweight title by knocking out George Foreman in the eighth round in Kinshasa, Zaire. Dubbed the 'Rumble in the Jungle,' Ali used his 'rope-a-dope' tactic, leaning on the ropes to absorb Foreman’s punches while conserving energy. Foreman, the undefeated champion, tired by the seventh round in the humid heat. Ali then unleashed a flurry, ending with a right hand that floored Foreman. At 32, Ali defied odds as a 4-1 underdog, regaining the crown he’d lost in 1967.\n\nThe fight, promoted by Don King, drew global attention, with 60,000 fans chanting 'Ali, bomaye!' (kill him). Foreman’s power had intimidated opponents, but Ali’s strategy and taunts broke him. The victory was a cultural milestone, showcasing Ali’s charisma and resilience. Broadcast to millions, it remains boxing’s most famous upset. For Ali, it was a triumphant return, proving he was still 'The Greatest.'"),
        
        Moment(id: 24, title: "Tyson’s 91-Second KO", text: "On June 27, 1988, Mike Tyson knocked out Michael Spinks in 91 seconds to unify the heavyweight titles at Atlantic City’s Convention Hall. Tyson, the WBA and WBC champ, faced Spinks, the IBF and lineal champ, in a clash of undefeated titans. At 21, Tyson landed a devastating right uppercut and left hook, dropping Spinks twice. The second knockdown ended it—Spinks couldn’t beat the count. Tyson earned $20 million, cementing his reign as boxing’s most feared fighter.\n\nSpinks, a light heavyweight legend, moved up but couldn’t handle Tyson’s speed and power. The crowd erupted as the fight ended almost before it began. Tyson’s 35-0 record (31 KOs) underscored his dominance. The brevity of the bout became legendary, a symbol of his peak ferocity. For boxing, it was a high-water mark of the heavyweight division’s glamour."),
        
        Moment(id: 25, title: "Sugar Ray Leonard’s 1987 Comeback", text: "On April 6, 1987, Sugar Ray Leonard returned from a three-year retirement to upset Marvin Hagler for the WBC middleweight title in Las Vegas. Leonard, 30, won a split decision—116-112, 115-113, 113-115—after 12 rounds of tactical brilliance. Hagler, the dominant champ with a 62-2-2 record, was favored heavily. Leonard danced and flurried, stealing rounds despite Hagler’s pressure. The fight, at Caesars Palace, drew 15,000 fans and millions on PPV.\n\nLeonard had fought just once since 1982 due to a detached retina, making his win stunning. Hagler landed harder shots, but Leonard’s showmanship swayed judges. The controversial decision still sparks debate—many felt Hagler deserved it. Leonard’s charisma and courage shone, reviving his career. For boxing, it was a classic, pitting two legends in a thrilling showdown."),
        
        Moment(id: 26, title: "Joe Louis’ 1938 Revenge", text: "On June 22, 1938, Joe Louis knocked out Max Schmeling in the first round at Yankee Stadium, avenging his only loss. Schmeling had beaten Louis in 1936, a propaganda coup for Nazi Germany. In the rematch, Louis landed 41 punches in 124 seconds, dropping Schmeling three times. The final right to the jaw ended it, with 70,000 fans roaring. Louis retained his heavyweight title, held since 1937, in a fight with racial and political weight.\n\nSchmeling, a German hero, faced Louis, a Black American icon, amid rising global tensions. Louis trained ruthlessly, driven by redemption. The KO was a blow to Hitler’s regime, which had touted Schmeling’s earlier win. Broadcast worldwide, it uplifted Black Americans during segregation. For Louis, it was a defining moment, solidifying his legacy as a champion and symbol."),
        
        // MMA
        Moment(id: 27, title: "McGregor’s 13-Second KO", text: "On December 12, 2015, Conor McGregor knocked out Jose Aldo in 13 seconds to win the UFC featherweight title at UFC 194 in Las Vegas. Aldo, unbeaten for a decade, charged forward, but McGregor countered with a left hand that dropped him cold. A few hammerfists sealed it, the fastest finish in UFC title history. McGregor, 27, became the first Irish UFC champion, fulfilling his brash predictions. The MGM Grand crowd erupted as Aldo lay stunned.\n\nThe buildup was intense—two years of trash talk and a canceled fight hyped the clash. Aldo, with an 18-1 record, was the division’s king, while McGregor was 6-0 in the UFC. The KO validated McGregor’s precision and swagger, launching him to superstardom. It remains a benchmark for MMA’s unpredictability. For the UFC, it was a landmark moment, boosting its global reach."),
        
        Moment(id: 28, title: "Rousey’s UFC Debut", text: "On February 23, 2013, Ronda Rousey made history in the UFC’s first women’s fight, submitting Liz Carmouche in 4:49 at UFC 157 in Anaheim. Rousey, the Strikeforce champ, defended her bantamweight title with her signature armbar. Carmouche nearly mounted a comeback with a choke, but Rousey escaped and locked in the hold. The Honda Center crowd roared as women’s MMA debuted in the UFC. Rousey, 26, became the sport’s first female star.\n\nUFC president Dana White, once skeptical of women fighting, embraced Rousey’s charisma and skill. She’d won bronze in judo at the 2008 Olympics, bringing credibility. Carmouche, a Marine veteran, was a tough test, but Rousey’s dominance shone. The win sparked a women’s MMA boom, with Rousey headlining over Jon Jones that night. For the sport, it was a seismic shift, proving women belonged in the Octagon."),
        
        Moment(id: 29, title: "Silva’s Front Kick KO", text: "On February 5, 2011, Anderson Silva knocked out Vitor Belfort with a front kick to the chin at UFC 126 in Las Vegas, defending his middleweight title. At 2:59 of Round 1, Silva’s kick—straight from a martial arts movie—dropped Belfort, followed by punches for the finish. Silva, 35, was in his prime, with a 13-fight UFC win streak. The Mandalay Bay crowd gasped at the highlight-reel KO. Belfort, a former champ, had no answer for Silva’s creativity.\n\nThe fight was hyped as Brazil vs. Brazil, pitting two legends. Silva’s taunting and precision frustrated Belfort, setting up the kick. Trained by Steven Seagal, Silva called it his proudest moment. The KO is iconic, replayed endlessly in MMA lore. For Silva, it reinforced his reign as the sport’s most dazzling fighter."),
        
        Moment(id: 30, title: "Khabib’s Undefeated Retirement", text: "On October 24, 2020, Khabib Nurmagomedov submitted Justin Gaethje with a triangle choke at 1:34 of Round 2 at UFC 254 in Abu Dhabi, then retired undefeated at 29-0. Defending his lightweight title, Khabib weathered Gaethje’s strikes before taking him down. The finish came swiftly, with Gaethje tapping out cold. Khabib, 32, broke down in tears, honoring his late father, Abdulmanap, who’d died months earlier. The ‘Fight Island’ crowd was hushed, witnessing history.\n\nKhabib had promised his mother he’d stop after this fight, keeping his word. Gaethje, a dangerous striker, was his toughest test since Conor McGregor. The win capped a career of dominance—13-0 in the UFC. His wrestling and humility set him apart, earning global respect. For MMA, it was the end of an era, as an unbeaten legend walked away.")
    ]
}
